using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;

namespace ClassExercise2
{ 
    internal class Numbers
    {
        int negativenumbers = 0;
        int positivenumbers = 0;
        public static int CountTheNegAndPostiveNumber(int[] AllNumbers)
        {
            for (int i = 0; i < AllNumbers.Length; i++)
            {
                if (AllNumbers[i] > 0)
                {
                   

                }
              
            } 
        } 
      
    }
}
